In [106]:
import pandas as pd
import numpy as np

# Set a random seed so everyone gets the same dataset
np.random.seed(42)

data = {
    "patient_id": [
        101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
        111, 112, 113, 114, 115, 116, 117, 118, 119, 120,
        121, 103, 107, 122, 123
    ],
    "animal_type": [
        "dog", "cat", "dog", "rabbit", "cat",
        "dog", "cat", "bird", "dog", "cat",
        "dog", "rabbit", "cat", "dog", "bird",
        "cat", "dog", "cat", "dog", "rabbit",
        "cat", None, "cat", "dog", "bird"
    ],
    "age_years": [
        3, 7, 2, 4, 1,
        5, 8, 2, 6, 3,
        None, 1, 4, 9, 3,
        2, 7, None, 4, 2,
        6, 2, 8, None, 1
    ],
    "weight_kg": [
        18.2, 4.1, 22.5, 1.8, 3.9,
        31.0, 4.7, 0.09, 14.3, 5.2,
        27.8, 2.1, 999.0, 10.5, 0.11,
        3.8, 24.1, 4.4, -5.0, 1.9,
        5.1, 22.5, 4.7, 16.3, 0.08
    ],
    "visit_reason": [
        "checkup", "checkup", "vaccination", "checkup", "dental",
        "injury", "checkup", "checkup", "dental", "vaccination",
        "checkup", "dental", "injury", "checkup", "vaccination",
        "injury", "vaccination", "checkup", "dental", "checkup",
        "vaccination", "vaccination", "checkup", "injury", "checkup"
    ],
    "visit_cost_usd": [
        85.0, 70.0, None, 65.0, 120.0,
        None, 75.0, 60.0, 130.0, 70.0,
        80.0, 115.0, 90.0, 85.0, 60.0,
        None, 95.0, 70.0, 125.0, 65.0,
        70.0, None, 75.0, 90.0, 60.0
    ],
    "follow_up_needed": [
        False, False, True, False, True,
        True, False, False, True, False,
        False, True, True, False, False,
        True, False, False, True, False,
        False, True, False, True, False
    ]
}

clinic = pd.DataFrame(data)
print("Dataset created. Shape:", clinic.shape)
clinic.head()

Dataset created. Shape: (25, 7)

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,101,dog,3.0,18.2,checkup,85.0,False
1,102,cat,7.0,4.1,checkup,70.0,False
2,103,dog,2.0,22.5,vaccination,NaN,True
3,104,rabbit,4.0,1.8,checkup,65.0,False
4,105,cat,1.0,3.9,dental,120.0,True

## Task 1

In [107]:
outlier_rows = clinic.loc[(clinic['weight_kg'] > 100) | (clinic['weight_kg'] < 0)]
print(outlier_rows)

    patient_id animal_type  age_years  weight_kg visit_reason  visit_cost_usd  \
12         113         cat        4.0      999.0       injury            90.0
18         119         dog        4.0       -5.0       dental           125.0

    follow_up_needed
12              True
18              True

In [108]:
clinic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        25 non-null     int64
 1   animal_type       24 non-null     object
 2   age_years         22 non-null     float64
 3   weight_kg         25 non-null     float64
 4   visit_reason      25 non-null     object
 5   visit_cost_usd    21 non-null     float64
 6   follow_up_needed  25 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

- 25 rows, 7 columns
- animal_type, age_years, visit_cost_usd
- it is a boolean value (True/False)

In [109]:
clinic.describe()

       patient_id  age_years   weight_kg  visit_cost_usd
count   25.000000  22.000000   25.000000       21.000000
mean   111.440000   4.090909   48.927200       83.571429
std      6.801225   2.524340  198.178411       21.974011
min    101.000000   1.000000   -5.000000       60.000000
25%    106.000000   2.000000    2.100000       70.000000
50%    111.000000   3.500000    4.700000       75.000000
75%    117.000000   6.000000   18.200000       90.000000
max    123.000000   9.000000  999.000000      130.000000

- the min is -5kg which is not possible
- the max is 999kg which is also not possible

In [110]:
clinic['visit_reason'].value_counts()

visit_reason
checkup        11
vaccination     6
dental          4
injury          4
Name: count, dtype: int64

- the most common reason for a visit is a checkup

## Task 2

In [111]:
clinic.isna()

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
5,False,False,False,False,False,True,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False
17,False,False,True,False,False,False,False
18,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False
21,False,True,False,False,False,True,False
22,False,False,False,False,False,False,False
23,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False

In [112]:
clinic.isna().sum()
# age_years and visit_cost_usd have the most missing values

patient_id          0
animal_type         1
age_years           3
weight_kg           0
visit_reason        0
visit_cost_usd      4
follow_up_needed    0
dtype: int64

## Task 3

In [113]:
clinic = clinic.dropna(subset=["animal_type"])

In [114]:
clinic.shape
#only one row was dropped, 24 remain

(24, 7)

## Task 4

In [115]:
median_age = clinic['age_years'].median()
print(median_age)

4.0

In [116]:
clinic['age_years'] = clinic['age_years'].fillna(median_age)

In [117]:
clinic["age_years"].isna().sum()

np.int64(0)

## Task 5

In [118]:
### Task 5
clinic["visit_cost_usd"] = clinic["visit_cost_usd"].fillna(clinic.groupby("visit_reason")["visit_cost_usd"].transform("median"))
clinic["visit_cost_usd"].isna().sum()

np.int64(0)

## Task 6

In [119]:
clinic[clinic["weight_kg"] > 200]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
12,113,cat,4.0,999.0,injury,90.0,True

In [120]:
clinic[clinic["weight_kg"] <= 0]

,patient_id,animal_type,age_years,weight_kg,visit_reason,visit_cost_usd,follow_up_needed
18,119,dog,4.0,-5.0,dental,125.0,True

In [121]:
clinic.loc[clinic["weight_kg"] <= 0, "weight_kg"] = np.nan

In [122]:
clinic.loc[clinic["weight_kg"] > 200, "weight_kg"] = np.nan

In [138]:
print(clinic.loc[[12,18]])

    patient_id animal_type  age_years  weight_kg visit_reason  visit_cost_usd  \
12         113         cat        4.0        NaN       injury            90.0
18         119         dog        4.0        NaN       dental           125.0

    follow_up_needed
12              True
18              True

In [124]:
clinic["weight_kg"].isna().sum()

np.int64(2)

In [125]:
clinic[clinic.duplicated()]

clinic = clinic.drop_duplicates()

In [126]:
clinic.shape

(23, 7)

## Task 8

In [127]:
#Task 8.1
clinic.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23 entries, 0 to 24
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   patient_id        23 non-null     int64
 1   animal_type       23 non-null     object
 2   age_years         23 non-null     float64
 3   weight_kg         21 non-null     float64
 4   visit_reason      23 non-null     object
 5   visit_cost_usd    23 non-null     float64
 6   follow_up_needed  23 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(2)
memory usage: 1.3+ KB

#### Drop two 2 rows
#### two null values in the weight column

In [128]:
#Task 8.2
clinic.isna().sum()

patient_id          0
animal_type         0
age_years           0
weight_kg           2
visit_reason        0
visit_cost_usd      0
follow_up_needed    0
dtype: int64

#### There are remaining null values in weight_kg

In [129]:
clinic.describe()

       patient_id  age_years  weight_kg  visit_cost_usd
count    23.00000  23.000000  21.000000       23.000000
mean    112.00000   4.000000   9.618095       83.913043
std       6.78233   2.276361   9.854323       21.157232
min     101.00000   1.000000   0.080000       60.000000
25%     106.50000   2.000000   2.100000       70.000000
50%     112.00000   4.000000   4.700000       80.000000
75%     117.50000   5.500000  16.300000       90.000000
max     123.00000   9.000000  31.000000      130.000000

In [130]:
#The weight_kg looks reasonable now

In [131]:
clinic.duplicated().sum()

np.int64(0)

## Discussion Questions
1. We drop animal_type is because a lot of other data in the DataFrame is dependent on what the animal_type is. We keep the null ages because the range of ages isn't very big, and animals besides humans and other large mammals tend to live around the same amount of time. However, we can use different methods to clean the data depending on what we use it for.
2. The data would not portray the correct image, as different reasons for visiting the clinic will result in different costs. Generalizing the cost to the median of the whole set could fill in accurate data where values are missing.
3. There were few issues that could be changed.

## Task 9

In [132]:
clinic["weight_kg"] = clinic["weight_kg"].clip(lower = 0.05, upper=80)

In [139]:
print(clinic.loc[[12,18]])

    patient_id animal_type  age_years  weight_kg visit_reason  visit_cost_usd  \
12         113         cat        4.0        NaN       injury            90.0
18         119         dog        4.0        NaN       dental           125.0

    follow_up_needed
12              True
18              True

In [133]:
clinic["weight_kg"].describe()

count    21.000000
mean      9.618095
std       9.854323
min       0.080000
25%       2.100000
50%       4.700000
75%      16.300000
max      31.000000
Name: weight_kg, dtype: float64

In [134]:
# if you fill in data with more accurate information the model is more robust.

## Task 10

In [144]:
clinic = clinic.dropna(subset = ["weight_kg"])

In [146]:
clinic.shape

(21, 7)